services:
    ##########################################################################################
    # NGINX - webserver
    ##########################################################################################
    nginx:
        image: nginx-${NGINX_VERSION}:docker-server
        container_name: nginx-${NGINX_VERSION}-${APP_HOST}
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${APP_CERTS_PATH}:/etc/nginx/ssl
            - ${NGINX_MAIN_CONF_PATH}nginx.conf:/etc/nginx/nginx.conf:ro
            - ${NGINX_MAIN_CONF_PATH}mime.types:/etc/nginx/mime.types:ro
            - ${NGINX_CONF_PATH}:/etc/nginx/templates
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        environment:
            - NGINX_PUBLIC_PATH=${NGINX_PUBLIC_PATH}
            - APP_HOST=${APP_HOST}
            - APP_CERT=${APP_CERT}
            - APP_CERT_KEY=${APP_CERT_KEY}
            - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
            - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
            - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
            - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
            - NGINX_ENTRYPOINT_QUIET_LOGS=1
            - NGINX_PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
            - NGINX_PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
            - NGINX_PHP_UPSTREAM_SWOOLE_PORT=${NGINX_PHP_UPSTREAM_SWOOLE_PORT}
        restart: unless-stopped
        tty: true
        depends_on:
            - php
        command: [ "nginx" ]
        networks:
            docker-server:
            nginx-proxy-external:
                aliases:
                    - ${APP_HOST}

    ##########################################################################################
    # Node.js
    ##########################################################################################
    nodejs:
        image: nodejs-${NODEJS_VERSION}:docker-server
        container_name: nodejs-${NODEJS_VERSION}-${APP_HOST}
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        restart: unless-stopped
        tty: true
        user: node
        working_dir: /var/www
        environment:
            TZ: ${NODEJS_TIMEZONE}
        networks:
            - docker-server

    ##########################################################################################
    # PHP
    ##########################################################################################
    php:
        image: php-${PHP_VERSION}:docker-server
        container_name: php-${PHP_VERSION}-${APP_HOST}
        restart: unless-stopped
        tty: true
        user: www-data
        working_dir: /var/www
        environment:
            PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
            TZ: ${PHP_TIMEZONE}
            COMPOSER_HOME: "/dev/null"
            DEVELOPMENT_PORT: ${VITE_APP_PORT}
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ./server/php/${PHP_VERSION}/php-ini/custom.d:/usr/local/etc/php/custom.d:ro
            - ./server/php/${PHP_VERSION}/extensions:/usr/local/etc/php/custom.d:ro
            - ./server/php/${PHP_VERSION}/php-ini/php.ini:/usr/local/etc/php/php.ini:ro
            - ./server/php/${PHP_VERSION}/fpm-conf/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
            - ./server/php/${PHP_VERSION}/fpm-conf/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
        networks:
            - docker-server

    ##########################################################################################
    # PHP-CLI
    ##########################################################################################
    php-cli:
        image: php-cli-${PHP_VERSION}:docker-server
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        networks:
            - docker-server

    ##########################################################################################
    # MySQL (MariaDB)
    ##########################################################################################
    mysql:
        image: mariadb-${MYSQL_VERSION}:docker-server
        container_name: mariadb-${MYSQL_VERSION}-${APP_HOST}
        restart: unless-stopped
        tty: true
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_CHARSET=utf8mb4
            - MYSQL_COLLATION=utf8mb4_unicode_ci
            - TZ=${MYSQL_TIMEZONE}
        volumes:
            - ${HOST_DATA_PATH}/mysql:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        security_opt:
            - seccomp:unconfined
        networks:
            - docker-server

networks:
    docker-server:
        driver: bridge
        name: docker-server
    nginx-proxy-external:
        external: true
